DROP TABLE IF EXISTS users;
CREATE TABLE users (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  email TEXT NOT NULL
);

DROP TABLE IF EXISTS daily_roly_poly_direction_counts;
CREATE TABLE daily_roly_poly_direction_counts (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  date TEXT NOT NULL,
  east INTEGER NOT NULL DEFAULT 0,
  west INTEGER NOT NULL DEFAULT 0,
  south INTEGER NOT NULL DEFAULT 0,
  north INTEGER NOT NULL DEFAULT 0,
  FOREIGN KEY (user_id) REFERENCES users(id)
);

DROP TABLE IF EXISTS daily_others_counts;
CREATE TABLE daily_others_counts (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  date TEXT NOT NULL,
  dog INTEGER NOT NULL DEFAULT 0,
  cat INTEGER NOT NULL DEFAULT 0,
  butterfly INTEGER NOT NULL DEFAULT 0,
  FOREIGN KEY (user_id) REFERENCES users(id)
);
